In [6]:
import mysql.connector
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [ ]:
# create connection between jupyter notebook and mysql

In [7]:
engine = create_engine("mysql+pymysql://root:Monika1175#@localhost/Healthcare")

In [ ]:
# Read csv file and clean the data

In [8]:
df = pd.read_csv("Healthcare_dataset.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15  Length of Stay      55500 non-null  int64
dtypes: float64(1), int64(3), object(12)
memory usage: 6.8+ MB

In [10]:
df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay
0,Bobby Jackson,19,Female,AB+,Infections,1/31/2024,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2/7/2024,Azithromycin,Normal,7
1,Leslie Terry,15,Female,B-,Flu,8/20/2019,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,8/22/2019,Tamiflu,Abnormal,2
2,Danny Smith,50,Female,A+,Cancer,9/22/2022,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214060,205,Elective,10/30/2022,Cisplatin,Inconclusive,38
3,Andrew Watts,24,Female,O+,Asthma,11/18/2020,Kevin Wells,UI Health (University of Illinois Hospital),Aetna,4092.601229,450,Elective,11/19/2020,Prednisone,Normal,1
4,Adrienne Bell,80,Female,A+,Heart Disease,9/19/2022,Kathleen Hanna,Northwestern Memorial Hospital,Cigna,47985.660250,458,Routine,10/27/2022,Beta-blockers,Inconclusive,38
5,Emily Johnson,90,Male,O+,Alzheimer’s,12/20/2023,Taylor Newton,UI Health (University of Illinois Hospital),Medicare,37140.366420,389,Routine,3/18/2024,Donepezil,Abnormal,89
6,Edward Edwards,35,Female,O+,Flu,11/3/2020,Kelly Olson,UChicago Medicine,Cigna,557.697323,389,Emergency,11/5/2020,Zanamivir,Normal,2
7,Christina Martinez,12,Female,O+,Infections,12/28/2021,Suzanne Thomas,Northwestern Memorial Hospital,UnitedHealthcare,4180.642896,277,Routine,12/31/2021,Azithromycin,Abnormal,3
8,Jasmine Aguilar,54,Male,O-,Heart Disease,7/1/2020,Daniel Ferguson,Loyola University Medical Center,Medicare,31688.559770,316,Emergency,8/2/2020,Aspirin,Inconclusive,32
9,Christopher Berg,65,Male,O+,Cancer,5/23/2021,Heather Day,Northwestern Memorial Hospital,Aetna,52910.753720,249,Emergency,7/11/2021,Cisplatin,Inconclusive,49

In [11]:
df.describe()

                Age  Billing Amount   Room Number  Length of Stay
count  55500.000000    55500.000000  55500.000000    55500.000000
mean      48.001622    21835.044636    301.134829       17.841009
std       21.105827    23574.413594    115.243069       20.272294
min        5.000000      500.220989    101.000000        1.000000
25%       32.000000     4195.525741    202.000000        4.000000
50%       50.000000    11089.537760    302.000000        8.000000
75%       65.000000    35887.703407    401.000000       28.000000
max       90.000000    99997.797980    500.000000       89.000000

In [12]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Length of Stay        0
dtype: int64

In [13]:
df.duplicated().sum()

0

In [14]:
df.shape

(55500, 16)

In [15]:
df.size

888000

In [ ]:
# Strip extra spaces in column names

In [16]:
df.columns = df.columns.str.strip()

In [ ]:
# Change the column name and relplace ' ' with '_'

In [17]:
df.rename(columns={'Name': 'Patient Name'}, inplace=True)

In [18]:
df.columns = df.columns.str.replace(' ', '_')

In [19]:
df.dtypes

Patient_Name           object
Age                     int64
Gender                 object
Blood_Type             object
Medical_Condition      object
Date_of_Admission      object
Doctor                 object
Hospital               object
Insurance_Provider     object
Billing_Amount        float64
Room_Number             int64
Admission_Type         object
Discharge_Date         object
Medication             object
Test_Results           object
Length_of_Stay          int64
dtype: object

In [ ]:
# Change the formate of Admission Date and Discharge Date in YYYY-MM-DD

In [22]:
df['Date_of_Admission'] = pd.to_datetime(df['Date_of_Admission']).dt.strftime('%Y-%m-%d')

In [23]:
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date']).dt.strftime('%Y-%m-%d')

In [ ]:
# Change the data type from object to date for both the column

In [24]:
date_cols = ['Date_of_Admission', 'Discharge_Date']

for col in date_cols:
    df[col] = pd.to_datetime(df[col])

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_Name        55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood_Type          55500 non-null  object
 4   Medical_Condition   55500 non-null  object
 5   Date_of_Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance_Provider  55500 non-null  object
 9   Billing_Amount      55500 non-null  float64
 10  Room_Number         55500 non-null  int64
 11  Admission_Type      55500 non-null  object
 12  Discharge_Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test_Results        55500 non-null  object
 15  Length_of_Stay      55500 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(3), object(10)
memory usage: 6.8+ MB

In [26]:
df.head()

,Patient_Name,Age,Gender,Blood_Type,Medical_Condition,Date_of_Admission,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Length_of_Stay
0,Bobby Jackson,19,Female,AB+,Infections,2024-01-31,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2024-02-07,Azithromycin,Normal,7
1,Leslie Terry,15,Female,B-,Flu,2019-08-20,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,2019-08-22,Tamiflu,Abnormal,2
2,Danny Smith,50,Female,A+,Cancer,2022-09-22,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214060,205,Elective,2022-10-30,Cisplatin,Inconclusive,38
3,Andrew Watts,24,Female,O+,Asthma,2020-11-18,Kevin Wells,UI Health (University of Illinois Hospital),Aetna,4092.601229,450,Elective,2020-11-19,Prednisone,Normal,1
4,Adrienne Bell,80,Female,A+,Heart Disease,2022-09-19,Kathleen Hanna,Northwestern Memorial Hospital,Cigna,47985.660250,458,Routine,2022-10-27,Beta-blockers,Inconclusive,38

In [ ]:
# change Alzheimer’s into Alzheimer in medical_condition column

In [27]:
df['Medical_Condition'] = df['Medical_Condition'].replace(
    "Alzheimer’s",
    "Alzheimer"
)

In [28]:
df.head(20)

,Patient_Name,Age,Gender,Blood_Type,Medical_Condition,Date_of_Admission,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Length_of_Stay
0,Bobby Jackson,19,Female,AB+,Infections,2024-01-31,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2024-02-07,Azithromycin,Normal,7
1,Leslie Terry,15,Female,B-,Flu,2019-08-20,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,2019-08-22,Tamiflu,Abnormal,2
2,Danny Smith,50,Female,A+,Cancer,2022-09-22,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214060,205,Elective,2022-10-30,Cisplatin,Inconclusive,38
3,Andrew Watts,24,Female,O+,Asthma,2020-11-18,Kevin Wells,UI Health (University of Illinois Hospital),Aetna,4092.601229,450,Elective,2020-11-19,Prednisone,Normal,1
4,Adrienne Bell,80,Female,A+,Heart Disease,2022-09-19,Kathleen Hanna,Northwestern Memorial Hospital,Cigna,47985.660250,458,Routine,2022-10-27,Beta-blockers,Inconclusive,38
5,Emily Johnson,90,Male,O+,Alzheimer,2023-12-20,Taylor Newton,UI Health (University of Illinois Hospital),Medicare,37140.366420,389,Routine,2024-03-18,Donepezil,Abnormal,89
6,Edward Edwards,35,Female,O+,Flu,2020-11-03,Kelly Olson,UChicago Medicine,Cigna,557.697323,389,Emergency,2020-11-05,Zanamivir,Normal,2
7,Christina Martinez,12,Female,O+,Infections,2021-12-28,Suzanne Thomas,Northwestern Memorial Hospital,UnitedHealthcare,4180.642896,277,Routine,2021-12-31,Azithromycin,Abnormal,3
8,Jasmine Aguilar,54,Male,O-,Heart Disease,2020-07-01,Daniel Ferguson,Loyola University Medical Center,Medicare,31688.559770,316,Emergency,2020-08-02,Aspirin,Inconclusive,32
9,Christopher Berg,65,Male,O+,Cancer,2021-05-23,Heather Day,Northwestern Memorial Hospital,Aetna,52910.753720,249,Emergency,2021-07-11,Cisplatin,Inconclusive,49
10,Michelle Daniels,69,Female,A+,Alzheimer,2020-04-19,John Duncan,UChicago Medicine,Cigna,20958.504330,394,Emergency,2020-06-17,Memantine,Abnormal,59
11,Aaron Martinez,34,Female,O+,Asthma,2023-08-13,Douglas Mayo,UChicago Medicine,Aetna,4375.842802,288,Emergency,2023-08-18,Prednisone,Normal,5
12,Connor Hansen,68,Male,O+,Diabetes,2019-12-12,Kenneth Fletcher,UI Health (University of Illinois Hospital),Medicare,9958.047667,134,Emergency,2019-12-19,Metformin,Abnormal,7
13,Robert Bauer,55,Male,O+,Heart Disease,2020-05-22,Theresa Freeman,UI Health (University of Illinois Hospital),Cigna,46163.214100,309,Elective,2020-06-26,Aspirin,Inconclusive,35
14,Brooke Brady,45,Female,A+,Obesity,2021-10-08,Roberta Stewart,UChicago Medicine,UnitedHealthcare,13682.169800,182,Elective,2021-10-16,Phentermine,Normal,8
15,Ms. Natalie Gamble,56,Female,A+,Obesity,2023-01-01,Maria Dougherty,Loyola University Medical Center,UnitedHealthcare,13580.620540,465,Urgent,2023-01-08,Phentermine,Abnormal,7
16,Haley Perkins,80,Female,A+,Cancer,2020-06-23,Erica Spencer,UChicago Medicine,Medicare,38120.749600,114,Emergency,2020-08-12,Cisplatin,Abnormal,50
17,Mrs. Jamie Campbell,72,Female,A+,Alzheimer,2020-03-08,Justin Kim,Northwestern Memorial Hospital,Blue Cross,18973.756330,449,Routine,2020-04-03,Rivastigmine,Abnormal,26
18,Luke Burgess,51,Female,B-,Obesity,2021-03-04,Justin Moore Jr.,Loyola University Medical Center,Aetna,6705.580678,260,Elective,2021-03-08,Phentermine,Abnormal,4
19,Daniel Schmidt,13,Male,A+,Infections,2022-11-15,Denise Galloway,Loyola University Medical Center,UnitedHealthcare,4553.264999,465,Urgent,2022-11-17,Azithromycin,Abnormal,2

In [ ]:
# create new column for diseases risk category

In [29]:
df['risk_category'] = df['Medical_Condition'].apply(
    lambda x:
    'Critical' if x in ['Cancer', 'Heart Disease', 'Alzheimer']
    else 'High Risk' if x in ['Diabetes', 'Obesity', 'Asthma']
    else 'Low Risk'
)

In [30]:
df['age_group'] = df['Age'].apply(
    lambda x:
    'Child' if x <= 18
    else 'Young Adult' if x <= 35
    else 'Adult' if x <= 50
    else 'Senior Adult' if x <= 65
    else 'Elderly'
)

In [32]:
df.head(20)

,Patient_Name,Age,Gender,Blood_Type,Medical_Condition,Date_of_Admission,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Length_of_Stay,risk_category,age_group
0,Bobby Jackson,19,Female,AB+,Infections,2024-01-31,Matthew Smith,Northwestern Memorial Hospital,Blue Cross,2212.272701,328,Emergency,2024-02-07,Azithromycin,Normal,7,Low Risk,Young Adult
1,Leslie Terry,15,Female,B-,Flu,2019-08-20,Samantha Davies,UI Health (University of Illinois Hospital),UnitedHealthcare,3185.161388,265,Emergency,2019-08-22,Tamiflu,Abnormal,2,Low Risk,Child
2,Danny Smith,50,Female,A+,Cancer,2022-09-22,Tiffany Mitchell,UI Health (University of Illinois Hospital),Blue Cross,72055.214060,205,Elective,2022-10-30,Cisplatin,Inconclusive,38,Critical,Adult
3,Andrew Watts,24,Female,O+,Asthma,2020-11-18,Kevin Wells,UI Health (University of Illinois Hospital),Aetna,4092.601229,450,Elective,2020-11-19,Prednisone,Normal,1,High Risk,Young Adult
4,Adrienne Bell,80,Female,A+,Heart Disease,2022-09-19,Kathleen Hanna,Northwestern Memorial Hospital,Cigna,47985.660250,458,Routine,2022-10-27,Beta-blockers,Inconclusive,38,Critical,Elderly
5,Emily Johnson,90,Male,O+,Alzheimer,2023-12-20,Taylor Newton,UI Health (University of Illinois Hospital),Medicare,37140.366420,389,Routine,2024-03-18,Donepezil,Abnormal,89,Critical,Elderly
6,Edward Edwards,35,Female,O+,Flu,2020-11-03,Kelly Olson,UChicago Medicine,Cigna,557.697323,389,Emergency,2020-11-05,Zanamivir,Normal,2,Low Risk,Young Adult
7,Christina Martinez,12,Female,O+,Infections,2021-12-28,Suzanne Thomas,Northwestern Memorial Hospital,UnitedHealthcare,4180.642896,277,Routine,2021-12-31,Azithromycin,Abnormal,3,Low Risk,Child
8,Jasmine Aguilar,54,Male,O-,Heart Disease,2020-07-01,Daniel Ferguson,Loyola University Medical Center,Medicare,31688.559770,316,Emergency,2020-08-02,Aspirin,Inconclusive,32,Critical,Senior Adult
9,Christopher Berg,65,Male,O+,Cancer,2021-05-23,Heather Day,Northwestern Memorial Hospital,Aetna,52910.753720,249,Emergency,2021-07-11,Cisplatin,Inconclusive,49,Critical,Senior Adult
10,Michelle Daniels,69,Female,A+,Alzheimer,2020-04-19,John Duncan,UChicago Medicine,Cigna,20958.504330,394,Emergency,2020-06-17,Memantine,Abnormal,59,Critical,Elderly
11,Aaron Martinez,34,Female,O+,Asthma,2023-08-13,Douglas Mayo,UChicago Medicine,Aetna,4375.842802,288,Emergency,2023-08-18,Prednisone,Normal,5,High Risk,Young Adult
12,Connor Hansen,68,Male,O+,Diabetes,2019-12-12,Kenneth Fletcher,UI Health (University of Illinois Hospital),Medicare,9958.047667,134,Emergency,2019-12-19,Metformin,Abnormal,7,High Risk,Elderly
13,Robert Bauer,55,Male,O+,Heart Disease,2020-05-22,Theresa Freeman,UI Health (University of Illinois Hospital),Cigna,46163.214100,309,Elective,2020-06-26,Aspirin,Inconclusive,35,Critical,Senior Adult
14,Brooke Brady,45,Female,A+,Obesity,2021-10-08,Roberta Stewart,UChicago Medicine,UnitedHealthcare,13682.169800,182,Elective,2021-10-16,Phentermine,Normal,8,High Risk,Adult
15,Ms. Natalie Gamble,56,Female,A+,Obesity,2023-01-01,Maria Dougherty,Loyola University Medical Center,UnitedHealthcare,13580.620540,465,Urgent,2023-01-08,Phentermine,Abnormal,7,High Risk,Senior Adult
16,Haley Perkins,80,Female,A+,Cancer,2020-06-23,Erica Spencer,UChicago Medicine,Medicare,38120.749600,114,Emergency,2020-08-12,Cisplatin,Abnormal,50,Critical,Elderly
17,Mrs. Jamie Campbell,72,Female,A+,Alzheimer,2020-03-08,Justin Kim,Northwestern Memorial Hospital,Blue Cross,18973.756330,449,Routine,2020-04-03,Rivastigmine,Abnormal,26,Critical,Elderly
18,Luke Burgess,51,Female,B-,Obesity,2021-03-04,Justin Moore Jr.,Loyola University Medical Center,Aetna,6705.580678,260,Elective,2021-03-08,Phentermine,Abnormal,4,High Risk,Senior Adult
19,Daniel Schmidt,13,Male,A+,Infections,2022-11-15,Denise Galloway,Loyola University Medical Center,UnitedHealthcare,4553.264999,465,Urgent,2022-11-17,Azithromycin,Abnormal,2,Low Risk,Child

In [ ]:
# Now data is cleaned and ready to upload

In [ ]:
# Now we will upload data in SQL

In [33]:
df.to_sql("healthcare_data", engine, if_exists='replace', index=False)

55500